name       : sonnet
version    : 5.38.0
release    : 7
source     :
    - https://download.kde.org/stable/frameworks/5.38/sonnet-5.38.0.tar.xz : aa73bb8a599f7b2ed14c043726ffe2d6399f1fd9a3daa51f12685aae11baa58c
license    : LGPL-2.1
component  : programming
summary    : Multi-language spell checker.
description: |
    Multi-language spell checker.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
