name       : sonnet
version    : 5.53.0
release    : 26
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/sonnet-5.53.0.tar.xz : 286c4c377ab38f3c14ff807f7a471f803c691b1fb624cecee8e7c9df349b684a
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Multi-language spell checker
description: |
    Multi-language spell checker.
builddeps  :
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-spell-check-by-default.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
