name       : sonnet
version    : 5.101.0
release    : 70
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.101/sonnet-5.101.0.tar.xz : 6b03178b279ceed9a46742e87537fa23a43e3c471b7a73908564c20d42788ed0
homepage   : https://community.kde.org/Frameworks
license    :
    - BSd-3-Cluase
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.tools
summary    : Multi-language spell checker
description: |
    Multi-language spell checker.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Quick)
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-spell-check-by-default.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
