name       : sonnet
version    : 5.94.0
release    : 66
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.94/sonnet-5.94.0.tar.xz : 8c570a64748d6bb6b91dff6fbf5e0cc5da7634c9a6f867944e99442066b7474c
homepage   : https://community.kde.org/Frameworks
license    :
    - BSd-3-Cluase
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.tools
summary    : Multi-language spell checker
description: |
    Multi-language spell checker.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Quick)
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-spell-check-by-default.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
