name       : sonnet
version    : 5.75.0
release    : 47
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.75/sonnet-5.75.0.tar.xz : 626055b262b3a43e6e947cf7f0383565324f42d6b24ab07b98c6cf054271c9e0
homepage   : https://community.kde.org/Frameworks
license    :
    - BSd-3-Cluase
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.tools
optimize   : lto
summary    : Multi-language spell checker
description: |
    Multi-language spell checker.
builddeps  :
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-spell-check-by-default.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
