name       : sonnet
version    : 5.68.0
release    : 41
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.68/sonnet-5.68.0.tar.xz : 079c4f5fcb9fe670e1242b18648e178aaa01eb81dbdfc881805eea1ec585bd67
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.tools
optimize   : lto
summary    : Multi-language spell checker
description: |
    Multi-language spell checker.
builddeps  :
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-spell-check-by-default.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
