name       : sonnet
version    : 5.40.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.40/sonnet-5.40.0.tar.xz : 68f2aa79b06a6ae61aa36133cf00342c8c513bfd9fb761363db7956edf3c24a9
license    : LGPL-2.1
component  : programming
summary    : Multi-language spell checker
description: |
    Multi-language spell checker.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-spell-check-by-default.patch
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
