name       : sonnet
version    : 5.59.0
release    : 32
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.59/sonnet-5.59.0.tar.xz : f30e4d622bed2979bdd140adc6fdd537c3bd7f632f49d9efec7d9789cdcff025
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Multi-language spell checker
description: |
    Multi-language spell checker.
builddeps  :
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-spell-check-by-default.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
