name       : sonnet
version    : 5.46.0
release    : 18
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.46/sonnet-5.46.0.tar.xz : 4490abfc7f0ae461d243db5179010d7821612de750ac2a7cc98731ee70f4558e
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Multi-language spell checker
description: |
    Multi-language spell checker.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %patch -p1 < $pkgfiles/0001-Enable-spell-check-by-default.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
