name       : sonnet
version    : 5.49.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.49/sonnet-5.49.0.tar.xz : 63053a671a8dc7a2a97cd49fe915e02e4b37fe41a06f3cd8785a7218d4acb754
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Multi-language spell checker
description: |
    Multi-language spell checker.
builddeps  :
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-spell-check-by-default.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
