name       : sonnet
version    : 5.51.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/sonnet-5.51.0.tar.xz : 44fd0f4031a371c04a22ff13fb98a07e043323716489fe68d317eb8b4cd05917
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Multi-language spell checker
description: |
    Multi-language spell checker.
builddeps  :
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-spell-check-by-default.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
