name       : sonnet
version    : 5.42.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.42/sonnet-5.42.0.tar.xz : 3c523fa0195e2e2af0071235507a9e30d140175afb4bc0e944d5025f5bab6ae4
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Multi-language spell checker
description: |
    Multi-language spell checker.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-spell-check-by-default.patch
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
