name       : sonnet
version    : 5.71.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.71/sonnet-5.71.0.tar.xz : cd663b3e1b23aef58d85f72dfdc92aaae33f358b22ad1fc36fde6c66eb7f0e72
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.tools
optimize   : lto
summary    : Multi-language spell checker
description: |
    Multi-language spell checker.
builddeps  :
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-spell-check-by-default.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
