name       : sonnet
version    : 5.62.0
release    : 35
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.62/sonnet-5.62.0.tar.xz : a1a2d3500d7fc51d94fd6f9d951c83be86436284aeda8416963fc5213956a69a
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Multi-language spell checker
description: |
    Multi-language spell checker.
builddeps  :
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-spell-check-by-default.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
