name       : sonnet
version    : 5.81.0
release    : 54
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.81/sonnet-5.81.0.tar.xz : 4a7c4e4d3da2df50004565c76ce0334697b941bd011be08fed7d91f96c37364e
homepage   : https://community.kde.org/Frameworks
license    :
    - BSd-3-Cluase
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.tools
summary    : Multi-language spell checker
description: |
    Multi-language spell checker.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-spell-check-by-default.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
