name       : sonnet
version    : 5.99.0
release    : 68
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.99/sonnet-5.99.0.tar.xz : f3f18e00f9205cfcf7d6923ccdbec480001da86f39623fe012773ee63afca7e4
homepage   : https://community.kde.org/Frameworks
license    :
    - BSd-3-Cluase
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.tools
summary    : Multi-language spell checker
description: |
    Multi-language spell checker.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Quick)
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-spell-check-by-default.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
