name       : sonnet
version    : 5.52.0
release    : 25
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.52/sonnet-5.52.0.tar.xz : 11037f2ca098dd389fd22fdf6ce2bf13f6429895e85dbfb740cc289e590be1a8
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Multi-language spell checker
description: |
    Multi-language spell checker.
builddeps  :
    - pkgconfig(hunspell)
    - pkgconfig(libvoikko)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-spell-check-by-default.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
