name       : sonnet
version    : 5.28.0
release    : 3
source     :
    - http://download.kde.org/stable/frameworks/5.28/sonnet-5.28.0.tar.xz : c83791acc41250d05d19471472bb9a862414a30721142df0b4d28810f71cf6ef
license    : LGPL-2.1
component  : programming
summary    : Multi-language spell checker.
description: |
    Multi-language spell checker.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(hunspell)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
