name       : sonnet
version    : 5.32.0
release    : 4
source     :
    - http://download.kde.org/stable/frameworks/5.32/sonnet-5.32.0.tar.xz : d11f917327fbe31a1a9666c560b4c4b49e6b38a3d104afe97daefcb110d9529f
license    : LGPL-2.1
component  : programming
summary    : Multi-language spell checker.
description: |
    Multi-language spell checker.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(hunspell)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
